name: Heroes of the Storm
favicon: null
layout_spectrum: 0
typography_spectrum: 0.24836
title: Heroes of the Storm
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#0087fc'
    - '#712426'
    - '#0062c0'
    - '#e4f4fc'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: 25dc699a-1a59-4bfc-8055-c0fcd923576e
    url: null
